### ISSUE TITLE
Consistency between event ItemSold price per item and the amount actually transferred in _buyItem

### ISSUE THREAD

**Issue by zajomi** [ghoul-sol/treasure-marketplace#1]
Right now in `_buyItem` the price per item included in the `ItemSold` event is the currently listed price, but going a few lines down to the actual transfer, the price per item used to calculate the amount transferred is actually the price per item specified by the buyer in calling `buyItem`. This buyer-specified amount can be greater than the currently listed price. So in that case there would be a mismatch between the event and what actually happened.

This could be fixed by either (1) having the `ItemSold` event use `_pricePerItem` instead of `listedItem.pricePerItem`, or (2) having the amount transferred always use the currently listed price when that is lower than the amount specified by the buyer.

**Comment by ghoul-sol** [comment]
Using `_pricePerItem` for `ItemSold` event makes sense for consistency.

However, it will be still the same value because `_pricePerItem` is `listedItem.pricePerItem` given as an argument in https://github.com/ghoul-sol/treasure-marketplace/blob/1b54482d0245e11ef6a968287833d69af39a7322/contracts/TreasureMarketplace.sol#L266

The goal is that we check if `_pricePerItem` provided by user is less or equal to `listedItem.pricePerItem` and `listedItem.pricePerItem` is used going forward. In case the price is lower, we don't the user to overpay. Perhaps it makes sense to rename it to `_maxPricePerItem`.

**Comment by zajomi** [comment]
Ah right yeah I see how I misinterpreted. Yeah I think `_maxPricePerItem` would be clearer, though there might be other reasons to keep it as it is.
